FROM mysql:latest

# Variables d'environnement pour configurer la base de données
ENV MYSQL_DATABASE=mydb
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=mypassword
ENV MYSQL_ROOT_PASSWORD=mypassword

# Définir le volume pour conserver les données
VOLUME /var/lib/mysql
